howsoai/howso-engine-py

- README.md
- Tweak README to be more inclusive.
> 17477: Tweak README

- howso/client/tests/test_client.py
updating tests for get_params and set_params to test new functionality
> 17406: Update tests for get_params and set_params

- .github/workflows/build-test-package.yml
- .github/workflows/create-branch-build.yml
- .github/workflows/get-dependency-details.yml
- .github/workflows/pytest.yml
Branch builds can now set a custom dependency to use for building/testing/etc.
> 17483: Adds new custom depends logic in branch builds

- Makefile
- howso/client/client.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/installation_verification.py
- howso/utilities/monitors.py
Migrate the top-level key `Howso` to `howso` if present.
> 17600: allow `howso` as top level key

- Makefile
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/installation_verification.py
- howso/utilities/monitors.py
Refactor to improve code quality and clarity.
> 17591: Code cleanups, minor refactoring

- howso/client/tests/test_client.py
- howso/direct/client.py
- howso/engine/trainee.py
- howso/scikit/scikit.py
Removing prediction residual conviction as a react detail
> 17587: Removes prediction residual conviction from React details, MAJOR

- README.md
Added dynamic logo support for dark mode
Updated introduction language
> 17734: Updated Readme

- howso/direct/client.py
- howso/engine/trainee.py
- howso/scikit/scikit.py
Updating docstrings to inform users about the directional contributions that are also returned when using this detail.
> 17877: Updates docstrings for feature contribution react details

- .github/templates/version_summary.md
- .github/workflows/build.yml
- .github/workflows/get-dependency-details.yml
- .github/workflows/workflow-summary.yml
* Includes additional information in the workflow summary page
* Embeds commit SHA, URL metadata into packaged `version.json` file
> 17808: Adds workflow summary improvements

- .github/workflows/build.yml
- .github/workflows/create-branch-build.yml
- .github/workflows/create-pr-build.yml
- .github/workflows/create-release-build.yml
- .github/workflows/get-dependency-details.yml
- .github/workflows/pepify.yml
- .github/workflows/pytest.yml
- .github/workflows/workflow-summary.yml
* Removes some workflow deprecation warnings by updating the default `checkout` Action to a newer version
* Truncates PR titles in workflow summary output
> 17808: Removes workflow deprecation warnings

- howso/utilities/installation_verification.py
Instead checks that Validator encountered no errors.
> 18117: Removes desirability check from Validator installation verification script

- LICENSE-3RD-PARTY.txt
- howso/direct/client.py
- howso/engine/trainee.py
- howso/scikit/scikit.py
Adds a description of the details key "features" which allows users to only request details for specific features (saving compute in non-robust applications)
> 17881: Adds features to details docstring MINOR

- LICENSE-3RD-PARTY.txt
- pyproject.toml
- requirements-3.10.txt
- requirements-3.11.txt
- requirements-3.8.txt
- requirements-3.9.txt
- version.json
Versions bumps for OSS release.
> 18493: Bumps amalgam-lang, howso-engine, howso-openapi-client versions

- LICENSE-3RD-PARTY.txt
- howso/direct/client.py
- requirements-3.10.txt
- requirements-3.11.txt
- requirements-3.8.txt
- requirements-3.9.txt
Updates the logic behind parameter validation in `react_series` to reflect the recent improvements on this front in the platform client.
> 18666: Updates parameter validation for react_series in direct client

- howso/engine/project.py
Added additional Project fields to the engine Project implementation for web clients.
> 18681: Added additional project fields to engine Project class, MINOR

- .github/workflows/build.yml
- LICENSE-3RD-PARTY.txt
Adds macOS arm64 tests and also re-enables linux and windows install verification on PRs.
> 18748: Adds macOS arm64 tests

- howso/client/base.py
- howso/client/client.py
- howso/client/configuration.py
- howso/client/feature_flags.py
- howso/client/tests/test_feature_flags.py
- howso/direct/client.py
- Added support for "feature_flags" section in configuration files.
- Added loading of configuration options to HowsoDirectClient during initialization.
> 18718: Support feature flags option in configuration file, MINOR

- howso/direct/client.py
- howso/engine/trainee.py
> 19148: Updates get_prediction_stats docstring for confusion_matrix now being sparse

- pyproject.toml
- requirements-3.10-dev.txt
- requirements-3.10.txt
- requirements-3.11-dev.txt
- requirements-3.11.txt
- requirements-3.8-dev.txt
- requirements-3.8.txt
- requirements-3.9-dev.txt
- requirements-3.9.txt
- version.json
Bumping versions of dependencies.
> 19090: Bumps amalgam-lang and howso-engine versions

- howso/utilities/feature_attributes/base.py
The check to see if a column is a YAML feature was raising on non-string types (like Booleans or floats).
> 19658: Improve YAML type-check

- version.json
Updating embedded howso-engine version to use the most recent release which contains a bugfix for flows using auto-ablation and auto-analysis.
> 19872: Updates embedded howso-engine version

- howso/engine/__init__.py
- howso/utilities/__init__.py
- howso/utilities/feature_attributes/__init__.py
- howso/utilities/utilities.py
Enhances automatic API generation by adding more items to some module's `__all__`s. Additionally sorts imports in some places.
> 19828: Enhances automatic API generation, MINOR

- howso/direct/core.py
- howso/utilities/internals.py
- requirements-3.10-dev.txt
- requirements-3.10.txt
- requirements-3.11-dev.txt
- requirements-3.11.txt
- requirements-3.12-dev.txt
- requirements-3.12.txt
- requirements-3.9-dev.txt
- requirements-3.9.txt
- version.json
Update the deserialization of responses from the engine. The new responses should have the following format:
```
// Success
[
1,
{
"warnings": ["a str message", ...], // optional warnings
"payload": Any
}
]
// Error
[  
0,
{
"detail": "single message" || ["or a list of messages", ...],
"code": "validation", // optional error code
"errors": { // optional field validation errors
"complex_object": {
"nested": {
"value": [
{
"message": "Value is not a valid integer.",
"code": "type_error.integer" // optional error code
}
]
},
}
"name": [
{
"message": "Field required.",
"code": "missing"
}
],
}
}
]
```
> 20105: Handle updated responses from engine

- howso/client/base.py
- howso/direct/client.py
- howso/engine/session.py
- howso/utilities/internals.py
- Improves some validation errors
- Fixes parameters to query session
> 21052: Update validation errors

- howso/utilities/feature_attributes/time_series.py
- howso/utilities/features.py
- howso/utilities/installation_verification.py
- howso/utilities/utilities.py
- Improves cleanup of Trainees if a failure occurs during installation verification
- Fixed some code linting errors
> 21309: Ensure trainees are cleaned up after installation verification

- howso/client/base.py
- howso/direct/client.py
- howso/engine/trainee.py
- howso/utilities/installation_verification.py
- howso/utilities/monitors.py
Trainee operations in the HowsoDirectClient may now raise HowsoValidationError if inputs failed validation checks.
> 21842: Support validation error objects from Engine responses, MINOR

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
- howso/utilities/utilities.py
* Implements additional logic in bounds calculation for time-only features that will improve its accuracy
* Enhances testing for time-only features
* Adds a few more auto-inferable time formats
* Minor bugfixes
> 21914: Fixes feature bounds computation for time features (IFA), additional testing

- LICENSE-3RD-PARTY.txt
- howso/client/api.py
- howso/client/tests/test_client.py
- howso/direct/client.py
- howso/direct/schemas/__init__.py
- howso/direct/schemas/trainee.py
- howso/direct/tests/test_standalone.py
- howso/engine/tests/test_engine.py
- howso/engine/trainee.py
- pyproject.toml
- requirements-3.10-dev.txt
- requirements-3.10.txt
- requirements-3.11-dev.txt
- requirements-3.11.txt
- requirements-3.12-dev.txt
- requirements-3.12.txt
- requirements-3.9-dev.txt
- requirements-3.9.txt
- version.json
If a Trainee is created with persistence='always', uses the Amalgam transactional mode to do incremental writes to the file, rather than always writing out a complete file on every action.
> 22329: Use transactional mode in the direct client

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/relational.py
- Fixes issue with bounds checking for relational
- Removes an outdated comment
> 23033: Fixes bounds-check for relational

- howso/client/base.py
- howso/engine/trainee.py
- version.json
- Adds docstrings and signature support for `use_sdm`
> 23059: Adds support for new analyze param - MINOR

- howso/client/base.py
- howso/engine/trainee.py
Adds parameters to react_group that allow users to specify trained cases to react to. Also updates the embedded engine version to the version that includes this functionality.
> 23537: Adds `conditions` and `case_indices` parameters to `react_group`, MAJOR

- LICENSE-3RD-PARTY.txt
- howso/client/base.py
- howso/engine/trainee.py
- pyproject.toml
- requirements-3.10-dev.txt
- requirements-3.10.txt
- requirements-3.11-dev.txt
- requirements-3.11.txt
- requirements-3.12-dev.txt
- requirements-3.12.txt
- requirements-3.13-dev.txt
- requirements-3.13.txt
- requirements-3.9-dev.txt
- requirements-3.9.txt
- version.json
Adds the `forecast_window_length` parameter to `react_aggregate`, which allows users to measure the accuracy of forecasts over a specified length
> 23642: Adds `forecast_window_length` parameter to `react_aggregate`, MINOR

- howso/utilities/feature_attributes/base.py
> 24124: Fixes bug where erroneous warning would appear when validating time-only features with IFA

- howso/utilities/installation_verification.py
```
❯ python -m howso.utilities.installation_verification
Validating Howso™ Installation
Python version: 3.11.5
Client type: HowsoPlatformClient
Client version: 79.2.36
API client version: 41.1.2.dev0+gc9fd983.d20250808
Platform version: 2025.3.0
Python: Running correctly (not under emulation) - OK ✔
Howso Client: Configuration                     - OK ✔
Howso Client: Basic react                       - OK ✔
Howso Client: Network latency                   - OK ✔
Howso Client: System performance                - OK ✔
Howso Client: Overridable resources             - OK ✔
Howso Engine™: Basic operations                 - OK ✔
All checks complete                             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:03:13
You are ready to use Howso™!
```
```
❯ python -m …
```
> 24235: Adds overridable resources check in installation_verification
