howsoai/howso-engine-py

- howso/direct/core.py
Renaming the parameter on get_internal_parameters to `action_feature` rather than `feature`. Reflecting that change here.
> 17371: Change a key of the passed JSON to the Engine on get_internal_parameters

- howso/utilities/feature_attributes/pandas.py
Now, instead of warning on some number of digits of precision, which varies on a number of other factors, raise when the byte representation requires more than 8 bytes. Also raise a warning if the float dtype is custom and doesn't have a `itemsize` defined.
> 17562: Improved conditions when a warning is raised about float precision in infer_feature_attributes

- howso/utilities/installation_verification.py
Return an exit code of 255 on critical errors, 0 for no critical errors.
> 17579: Adds exit codes to installation_verification

- howso/client/base.py
- howso/client/tests/test_client.py
- howso/direct/client.py
- howso/direct/core.py
- howso/engine/trainee.py
- pyproject.toml
- version.json
Adding our usual condition parameters ('condition', 'num_cases', and 'precision') to get_marginal_stats, which lets users find marginal stats on subsets of the data matching their condition.
> 16846: Adds parameters to `get_marginal_stats` to support conditioned stats, MINOR

- .github/workflows/build.yml
Adds the correct deployment and permissions settings to the release job so that PyPi recognizes this repository as a trusted publisher.
> 17617: Adjust release builds for PyPi trusted publishing

- howso/direct/client.py
the order of analyze_growth_factor and auto_analyze_limit_size was flipped in the method being called, so when the TS RL recipe was intending to set the analyze limit size, it was instead setting the growth factor.
> 17692: Fixes order of parameters passed into auto_analyze_params

- howso/utilities/internals.py
Should core return an empty warning dict. Ignore it rather than raise a TypeError.
> 17710 - Ignore empty warning dicts from core

- howso/utilities/features.py
- howso/utilities/internals.py
- howso/utilities/tests/test_internals.py
When using the to_pydatetime() method from pandas, emits a FutureWarning. There is no fix for this, as using the suggested alternative method still results in this FutureWarning being emitted. PR creates a subclass to reduce code clutter for this and future situations where Warnings need to be ignored
> 17716: Ignore future warnings for pandas to_pydatetime method.

- howso/client/client.py
- howso/client/configuration.py
- howso/client/tests/test_client.py
- howso/direct/client.py
This PR adds support for printing a helpful message when howso-engine is run without a configuration file.
This is the message that is displayed when there is no configuration file found.
> 17686: Print help for the user informing when no config was found

- .github/workflows/build.yml
- howso/__main__.py
- howso/client/__init__.py
- howso/client/tests/test_client.py
- howso/direct/client.py
Fixes version update suggestions for `howso-engine` to no longer use the legacy hardcoded `__version__`.
Also adds the `--break-system-packages` flag for arm64(_8a) verification install workflow jobs. This will fix the "externally managed environment" error seen on recent branch builds.
> 17794: Updates internal version checks to use new versioning scheme

- howso/direct/client.py
- version.json
Adds logic to work around some of the checks that were preventing time-series forecasting with discriminative parameters.
> 17854: Enables discriminative time-series forecasting

- howso/utilities/feature_attributes/base.py
If the attributes for a feature have "type"="continuous" and "data_type" is unspecified, then we expect those values to be numeric.
Here I add a check so that we catch if the values for a feature like this are not numeric. This was specifically raised when a user trained strings in a continuous feature without the "data_type"="string" attribute. Which broke a lot of stuff downstream.
> 17874: Adds check for non-numeric continuous features when 'data_type' is unspecified

- .github/templates/version_summary.md
- .github/workflows/build.yml
- .github/workflows/get-dependency-details.yml
- .github/workflows/workflow-summary.yml
* Adds version summary to all workflow runs
* Embeds display title and build date into `version.json` if a non-release `howso-engine` version is specified in a workflow input
> 17808: Adds workflow summary & branch build info to embedded version.json

- howso/direct/client.py
Removing the direct client limit on the amount of generative reacts that can be made with details requested.
> 18014: Drops the limit on generative reacts with details

- howso/client/tests/test_client.py
- howso/direct/client.py
- howso/engine/trainee.py
- howso/scikit/scikit.py
Deprecates "robust_computation" as a react detail and adds "robust_influences" and "robust_residuals" in its place. Added a deprecation warning and logic for when users give "robust_computation", which uses that specified value for both the new flags.
> 18041: Deprecates robust_computation, adds robust_influences and robust_residuals as details flags MINOR

- howso/direct/client.py
- howso/direct/core.py
- howso/engine/trainee.py
Fixing an incorrect parameter description for "action_feature" in the docstring of `Trainee.react_into_trainee`
All of the other instances of `react_into_trainee` had the correct description, so that version was copied here.
> 18538 Fixes the "action_feature" description in the docstring of `react_into_trainee`

- howso/direct/client.py
The docstring for continue_series_value states that when these values are specified, continue_series (the flag) would be treated as if it was true, but this logic wasn't properly captured in the code.
> 18601: Fixes an issue where continue_series flag is needed when continue_series_values are specified for discriminative forecasting

- LICENSE-3RD-PARTY.txt
- howso/direct/client.py
- requirements-3.10.txt
- requirements-3.11.txt
- requirements-3.8.txt
- requirements-3.9.txt
Using `validate_list_shape` raises a ValueError if the elements of `continue_series_values` have differing lengths, but this is acceptable input. I make the shift to instead use `num_list_dimensions`, which will not run into this problem.
> 18643: Fixes an issue where `continue_series_values` is a list of DataFrames with differing lengths

- .github/workflows/create-branch-build.yml
- .github/workflows/create-pr-build.yml
- .github/workflows/create-release-build.yml
Since other processes create tags on repos, this will ignore all tags that are not a semver release tag when determining next version.
> 18727: Updates git tag retrieval to skip non-repo tags

- howso/direct/core.py
This method was unintentionally removed from HowsoCore. Re-adding it here.
> 18756: Adds `get_session_indices` to HowsoCore MINOR

- .github/workflows/build.yml
- howso/direct/client.py
Fixes a bug where init/final_time_steps parameters were not being passed to the Howso Engine from the client when doing react_series with desired_conviction=None.
> 18910: Fixes an issue in passing init_time_steps and final_time_steps to the Engine during discriminative react_series calls

- howso/client/pandas/client.py
- howso/direct/client.py
- howso/engine/trainee.py
- howso/utilities/tests/test_utilities.py
- howso/utilities/utilities.py
New `Reaction` output type uses 'action' instead of 'series'. This renames all internal occurances
> 19143: Rename 'series' to 'action'

- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
Round the feature bounds to the same amount of decimal places that the feature values have.
This should prevent any issues where the bound has higher precision than the feature values allow. In this context, we sometimes see React returning values over the bound where they were synthed under, but rounding pushed them over.
> 19187: Rounds feature bounds to same precision as feature values

- howso/utilities/feature_attributes/relational.py
MSSQL requires an `order_by` when using an `OFFSET` or a non-simple `LIMIT` clause.
> 19234: Adds order_by to IFA relational queries

- howso/direct/client.py
- howso/direct/core.py
- howso/utilities/internals.py
- howso/utilities/monitors.py
Added memory limits for the request and response payload sizes when using batch scaling in react, react_series, and train. If the request or response size exceeds their respective limit, the batch size will be scaled down. If the size is within a threshold close to the limit (default 10%), the batch size will be prevented from scaling up, but may still scale down based on duration of the request.
> 19238: Improved batch scaling to account for memory

- howso/client/tests/test_client.py
This specific test calls Analyze on a Trainee that has never been trained with any cases. A new parameter validation in howso-engine now raises an error in this case.
I train a single value case into the Trainee so that the analyze is valid (more valid, at least) now.
> 19241: Fixes bad Analyze test

- .github/workflows/build.yml
Releasing `howso-engine-py` will now automatically trigger (1) a `howso-devcontainers` release of the same version, and (2) and PR to `howso-engine-recipes` that updates the `.devcontainer` folder with the new release version.
> 19225: Implements devcontainers release automation as part of release workflow

- howso/utilities/installation_verification.py
`react` now returns a `Reaction` class instance. This requires changes in the way we access cases from the result of a `react`.
> 19275: Adds compatibility with Reaction class

- howso/client/tests/test_client.py
Recent howso-engine changes alter the order of the default features when features parameters are not specified. This causes a few tests to fail now.
The solution is to specify the desired order of features as a parameter, fixing the test.
> 19320: Fixes tests by specifying features parameter as the desired order of features

- .github/workflows/build.yml
Fixes an issue where the devcontainers release would fail because it would be triggered before pushing the new `howso-engine` version to PyPi.
> 18744: Fixes bug in devcontainers release job

- .github/workflows/build.yml
Instead of validating the compatibility of the embedded howso-engine's Amalgam version with the _latest_ amalgam-lang-py's Amalgam version, introspect the specified amalgam-lang-py requirement and validate that version's Amalgam instead (via centralized workflow).
> 19427: Refactors Amalgam version validation in workflows

- howso/direct/client.py
- howso/direct/core.py
- howso/engine/trainee.py
This PR adds a new boolean flag to train named: "skip_auto_analyze"
When "skip_auto_analyze" is True, HSE may return a `"status": "analyze"` within the Train response. 
Client side, I have made the following changes:
- The direct client `train` method returns a boolean that indicates if the Trainee needs to analyze
- The Trainee object has a new property, 'needs_analyze' in which the response from the client is stored (also reset each call to train)
*This change makes it so that the client will not trigger any analyze calls automatically*.
> 19739: Adds boolean flag, "skip_auto_analyze" to `train`, MINOR

- howso/direct/core.py
- version.json
The error message on `load` was changed in previous commits. This broke a downstream test, this change reverts the message to be more similar to what it was before, fixing the aforementioned broken test.
> 20035: Updates error message on `load` to reflect previous message and updates Engine version

- howso/direct/core.py
Restores the correct filename for exported trainees.
> 20116: Restore trainee_id in output filename

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/infer_feature_attributes.py
- When `infer_feature_attributes` include the parameter `include_sample=True`, adds a "sample" key for each feature that includes a random sample of that feature, excluding nulls where possible.
- Adds `to_dataframe()` as a method. This allows one to see the feature attributes as a nicely presented table rather than a dictionary dump.
For example, below is the presentation of the resulting dataframe for the PMLB:iris dataset but with a random "datestamp" and "json" field added. This was called with `infer_feature_attributes()` and the dataframe was produced with `feature_attributes.to_dataframe()`.
The width of the dataframe's cells can easily be restricted in a notebook by using:
> pd.set_option('display.max_colwidth', 40)
This will auto-truncate long values such as the JSON string in …
> 20170: Adds sample and .to_dataframe() method to InferFeatureAttributesBase

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
`infer_feature_attributes` now specifies `data_type` for continuous features, and `allow_nulls=True` when before it would be left out entirely. This is so that the `to_dataframe()` function does not display these "missing" feature attributes as NaNs.
> 20276: Eliminates most NaNs from infer_feature_attributes output

- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
> 20358: Specifies formatted_date_time data_type in IFA for ISO string features

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
In cases where a Numpy dtype is returned for the `sample` of a feature's attributes, we need to make sure it is JSON serializable. After some discussion, it was agreed that this is for display only, so, a string representation is desired.
I considered all the available datatypes here:
Each have a solid `str()` implementation.
> 20332: Fix JSON serialization of `sample`s in feature attributes

- howso/client/tests/test_client.py
One test has a slightly incorrect detail name, fixing it.
> 20628: Fixes detail name used in a test

- howso/client/base.py
- howso/direct/client.py
- howso/direct/core.py
- howso/engine/trainee.py
These parameters are unused in the Engine so this PR removes them from the clients.
> 20615: Removes "preserve_session_data" and "session" parameters from `remove_cases`, MAJOR

- howso/direct/core.py
Removes `set_conviction_upper_threshold`, `set_conviction_lower_threshold`, and `clear_conviction_thresholds` methods from the HowsoCore. These methods were not exposed through the client or Trainee APIs.
These methods are being removed from the Engine as well, though they were already not supported in the clients and have not been functional.
> 20631: Removes methods regarding ablation conviction levels that are no longer functional, MAJOR

- howso/direct/client.py
- howso/direct/core.py
- version.json
Removes parameters that are no longer used by the Engine (and are consequently rejected).
> 20773: Removes 'separate_files' parameters from `export_trainee`

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/infer_feature_attributes.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/time_series.py
This PR improves `infer_feature_attributes` performance for large, dataframe-based datasets. In addition to reduced time to calculate, the memory overhead can also be reduced. The largest performance gains and memory reduction come from larger datasets.
For example:
A dataset with 27 columns and 69M rows:
- `0h52m27.8s / 12,781 MiB RAM` - without multiprocessing: 
- `0h09m01.5s /    793 MiB RAM` - with multiprocessing
This represents a performance _boost_ of 5.8X and a memory _reduction_ of 16X.
By default, IFR will automatically determine whether to use multi-processing. If the product of the dataset's  rows and columns is smaller than 25M cells, IFR will automatically _not_ use multi-processing as it is unlikely to be faster.
Multiprocessing can be forced `ON`, regardless of datasize by …
> 20725: Add multiprocessing to infer_feature_attributes for dataframes

- howso/direct/client.py
- Updated parameters to upgrade/export to be more consistent
- Upgrade now initializes an empty trainee before executing the upgrade
- An error message from load_entity is now exposed in the raised error
> 20992: Fixes upgrade trainee

- howso/utilities/installation_verification.py
Adds version information to the output of the installation verification script, and ensures that versioning information is put in the output stack trace in the case of an error.
> 21036: Adds version information to installation verification output and stacktrace

- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
When using multi-processing, a subset of the columns are processed in other processes. This PR filters the partial features passed in the `features` parameter to only those partial features relevant to the subset used in each process.
> 21108: Filter out unrelated partial features when multiprocessing

- howso/direct/core.py
- howso/engine/trainee.py
Not an API change, as `**kwargs` was technically in the API already, just not passed through all levels.
> 20491: Fixes experimental arguments being passed to reduce_data with kwargs

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
- Correctly assign `"data_type": "formatted_date_time"` when a datetime feature format is supplied.
- Correctly determine the bounds of a Pandas data frame datetime feature
- Significantly improve the performance of discovering bounds of Pandas data frame datetime features
> 21291: Improve datetime handling in infer_feature_attributes

- version.json
There was a bugfix in howso-engine, bringing it into the python package.
> 21586: Bumps howso-engine version

- howso/client/base.py
- howso/client/feature_flags.py
- howso/client/pandas/client.py
- howso/client/schemas/reaction.py
- howso/direct/_utilities.py
- howso/engine/trainee.py
- howso/scikit/scikit.py
- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/protocols.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/time_series.py
- howso/utilities/installation_verification.py
- howso/utilities/internals.py
- howso/utilities/json_wrapper.py
- howso/utilities/posix.py
- howso/utilities/testing.py
- howso/utilities/utilities.py
- Updates modules to bring them up to the latest typing standards
- Fixes feature conviction in the scikit package
> 21860: Improved type hinting

- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
Adds unit tests to ensure that IFA can handle feature names that are the same as base feature types (i.e., `nominal`, `ordinal`, `continuous`).
> 21832: Expands IFA unit tests for `types` around edge cases

- howso/client/base.py
- howso/engine/trainee.py
Renames the "session" parameter of #delete_session to "target_session" to help differentiate session parameters that indicate the active session of the user from parameters used to specify a specific non-active session.
> 22144: Renames "session" parameter of `delete_session()` to "target_session", MAJOR

- howso/client/base.py
- howso/client/typing.py
- howso/engine/trainee.py
Also adjusts the return value of `train` to accommodate multiple possible status messages.
> 21929: Adds max_num_cases, skip_reduce_data parameters to set_auto_ablation_params/train, MAJOR

- howso/client/base.py
When doing a generative series forecast using `react_series` and Dataframes as values for `continue_series_values`, incorrect values were being passed to the howso-engine. Column names were being passed instead of the serialized case values for each series. This fixes the issue.
> 22328: Fixes a bug when doing generative series forecasts using Dataframes for `continue_series_values`

- howso/utilities/feature_attributes/base.py
While it is only implemented in the `SingleTableFeatureAttributes` subclass, this will allow VSCode to autofill the method signature and display the docstring.
> 22385: Defines to_dataframe in `FeatureAttributesBase`, MINOR

- howso/utilities/__init__.py
- howso/utilities/monitors.py
- howso/utilities/tests/test_monitors.py
The state of a Timer can now be preserved as a frozen (Data) Class instance using the method `to_frozen_timer()`.
Also, adds some basic unit tests for Timer in general.
> 22560: Adds FrozenTimer dataclass MINOR

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/protocols.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
- to_json() now supports and `archive` flag which emits a richer object
- `to_json() now supports an optional `json_path` to write to disk
- `from_json()` is now available to accept JSON as a string or `json_path` for a file.
- `from_json()` auto-detects whether the JSON is an archival object and returns a FeatureAttributesBase or subclass.
- Adds tests `test_achival()` and `test_disk_archival()`
- Also fixes some glaring bugs related to `datetime` objects
> 22731: Support archival modes for feature attributes

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/relational.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
- version.json
- Adds `observed_min` to record the actual smallest value in each continuous feature.
- Adds `observed_max` to record the actual largest value in each continuous feature.
- Adds support for `observed_min/max` for ordinals as wel.
- Updates tests accordingly.
Depends on: https://github.com/howsoai/howso-engine/pull/415 ✅
> 22732: Adds observed bounds to feature attributes MINOR

- howso/client/base.py
- howso/engine/trainee.py
I took away a lot of the words and I hope the new sentence is more succinct and clear. The "new" functionality is that these parameters now apply to more than just computed prediction stats.
> 22717: Updates `react_aggregate`'s "context_condition" and "action_condition" docstrings to reflect new howso-engine functionality

- howso/client/base.py
- howso/client/tests/test_client.py
- howso/engine/tests/test_engine.py
- howso/engine/trainee.py
- version.json
Due to ablation, get_cases may not return cases in the original training order. Added documentation on how to sort cases if needed.
> 22631: Updates get_cases documentation

- howso/utilities/feature_attributes/relational.py
- Fixes a regression in an earlier release where min/max bounds were returned as Numpy types rather than Python floats from `infer_feature_attributes`.
> 22751: Fixes float type issue with relational IFA

- .github/workflows/build.yml
This will improve the reliability of the workflow.
> 22790: Updates Linux/ARM runner to use GitHub instead of emulator

- .github/workflows/build.yml
When `howso-engine-py` is released, the last step of the workflow is to initialize a "devcontainers" rebuild in `howso-engine-recipes`. Sometimes, however, this step fails because it tries to access the newly released `howso-engine-py` version before it is fully available on PyPi. We added a delay to mitigate this issue but it still happens occasionally. While this doesn't affect the release of `howso-engine-py` at all, it freaks people out. This PR will prevent the release workflow from appearing red when this happens.
> 23487: Adjusts devcontainers release step to continue on error

- howso/utilities/feature_attributes/tests/test_infer_feature_attributes_adc.py
This will allow non-enterprise users to run the entire test suite without error.
> 23545: Skips UTs with connectors repo if it is not installed

- howso/client/base.py
- howso/engine/trainee.py
- version.json
Adds a parameter to react group that allows users to compute the mean similarity conviction of the group of cases of interest.
> 23683: Adds `similarity_conviction` to `react_group`, MINOR

- howso/client/tests/test_infer_feature_attributes.py
- howso/utilities/feature_attributes/time_series.py
- Extends the signature to accept `default_time_zone` parameter.
- Adds a test of the above
- Adds `default_time_zone` to the docstring.
- Sorts the Parameters section of the docstring.
> 23780: Fixes InferFeatureAttributesTimeSeries

- howso/client/tests/test_infer_feature_attributes.py
- howso/utilities/feature_attributes/pandas.py
- howso/utilities/feature_attributes/tests/test_infer_feature_attributes.py
- howso/utilities/tests/test_features.py
Adds additional logic to `infer_feature_attributes` that checks whether a feature that is an instance of a Pandas `Timestamp` object has a time of 0:00:00, which indicates it is a date-only feature. In this case, our inferred datetime feature format should not include time information.
> 23934: Improves handling of time-only Timestamp features in IFA

- howso/client/tests/test_client.py
HSE will now raise an error when attempting to use features that don't exist, and one unit test in `howso-engine-py` needs to be updated to reflect this.
> 24125: Fixes outdated unit test failure due to new HSE error conditions

- howso/client/base.py
- howso/client/pandas/client.py
- howso/client/typing.py
- howso/engine/tests/test_engine.py
- howso/engine/trainee.py
Included a test this time around, mostly as a mechanism to ensure this doesn't merge without an updated Engine.
> 24265: Adds `get_value_masses` to Trainee and base client, MINOR

- howso/utilities/feature_attributes/base.py
- howso/utilities/feature_attributes/time_series.py
* Fixes a bug where determining the feature type for integers in time-series data would cause an error when multiprocessing is enabled in some cases
* Adjusts the threshold for the number of unique values that must be present in a feature for it to be deemed continuous
> 24430: Fixes bug in IFA where `max_workers>1` will break `_get_feature_type`, slightly adjusts continuous feature threshold

- hatch.toml
- howso/client/base.py
- howso/utilities/internals.py
- howso/utilities/tests/test_internals.py
If react, react_series, or react_series_stationary runs in batch mode, and the client practically supports running multiple requests in parallel, run each batch in a separate thread.
Reworks the batch scaler to have a cleaner interface.
Breaking Changes:
- Removed `batch_scaler_class` property of HowsoClient
> 24384: allow batched react to run in parallel, MAJOR

- howso/client/base.py
- howso/engine/trainee.py
- version.json
Marking as major because even though no breaking api changes were made to this project directly, the overall changes are breaking since the values are passed down and the version dependency bump makes this a breaking change for higher up the stack.
> 24515: Reformats references to custom code, MAJOR
